# model weight file path for save best model[str]
weight_fn : "./fully_connected_classifier.pth"
# cuda gpu id[int] ex. 0 or 1 / if you want cpu, insert -1
gpu_id : 0
# train, valid data split ratio[float]
train_ratio : .8
# number of epochs[int]
n_epochs : 1000
# number of batch size[int]
batch_size : 256
# epoch num for early stop, if lowest valid loss no change
early_stop : 50
# either use batch normalization
use_batch_norm : True
# if the use_batch_norm is False, model use dropout. So you should set dropout probability(p-hyperparameter)
dropout_p : .3

